spring:
  application:
    name: NSC Adapter
    
server:
  port: 8082
  
###########- Spring Actuator -#######
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always